// apps/studio/src/renderer/src/components/Inspector.tsx
import { useMemo } from "react";
import * as Select from "@radix-ui/react-select";
import * as Checkbox from "@radix-ui/react-checkbox";
import { Check, ChevronDown } from "lucide-react";
import {
  effectiveValue,
  instanceSize,
  requireDefinition,
  setProperty,
  setTransform,
  type GameObjectDefinition,
  type LevelObjectInstance,
  type PropertyMeta,
  type ValidationIssue,
} from "@mmx/content-schema";
import { editor, useEditorSnapshot } from "../app/useEditor.js";
import { SpritePreview } from "./SpritePreview.js";

interface Single {
  inst: LevelObjectInstance;
  def: GameObjectDefinition;
  width: number;
  height: number;
}

/** Right dock: schema-generated inspector with inline validation. */
export function Inspector() {
  const snap = useEditorSnapshot();
  const state = snap.state;

  const single = useMemo<Single | null>(() => {
    if (state.selectedIds.length !== 1) return null;
    const inst = state.document.objects.find((o) => o.id === state.selectedIds[0]);
    if (!inst) return null;
    const def = requireDefinition(inst.definitionId);
    const size = instanceSize(inst);
    return { inst, def, width: size.width, height: size.height };
  }, [state.selectedIds, state.document.objects]);

  const issues = useMemo<ValidationIssue[]>(() => {
    if (!single) return [];
    return snap.validation.issues.filter((i) => i.objectId === single.inst.id);
  }, [single, snap.validation]);

  const objectIssues = issues.filter((i) => !i.field);
  const hasIssue = (field: string) => issues.some((i) => i.field === field);
  const issueFor = (field: string) => issues.find((i) => i.field === field);

  const str = (inst: LevelObjectInstance, key: string): string => {
    const v = effectiveValue(inst, key);
    return v === undefined || v === null ? "" : String(v);
  };

  const onTransform = (s: Single, key: "x" | "y" | "width" | "height", raw: string): void => {
    const next = Number(raw);
    if (!Number.isFinite(next)) return;
    const before = key === "x" ? s.inst.x : key === "y" ? s.inst.y : s[key];
    if (next === before) return;
    editor.store.execute(setTransform(s.inst.id, { [key]: before }, { [key]: next }));
  };

  const onProp = (inst: LevelObjectInstance, prop: PropertyMeta, raw: string): void => {
    const next = prop.type === "number" ? Number(raw) : raw;
    if (prop.type === "number" && !Number.isFinite(next as number)) return;
    editor.store.execute(
      setProperty(inst.id, prop.key, "override", effectiveValue(inst, prop.key), next),
    );
  };

  const onBool = (inst: LevelObjectInstance, prop: PropertyMeta, checked: boolean): void => {
    editor.store.execute(
      setProperty(inst.id, prop.key, "override", effectiveValue(inst, prop.key) === true, checked),
    );
  };

  const onEnum = (inst: LevelObjectInstance, prop: PropertyMeta, value: string): void => {
    editor.store.execute(
      setProperty(inst.id, prop.key, "override", effectiveValue(inst, prop.key), value),
    );
  };

  const previewFlip = (s: Single) =>
    s.def.category === "enemy" && effectiveValue(s.inst, "FacesRight") === true;

  return (
    <div className="panel">
      <div className="scroll">
        {single ? (
          <>
            <div className="header">
              <SpritePreview
                definitionId={single.def.id}
                size={56}
                flip={previewFlip(single)}
                fallbackColor={single.def.editor.color}
              />
              <div className="title">
                <span className="name">
                  {single.def.icon} {single.def.name}
                </span>
                <span className="id">{single.inst.id}</span>
              </div>
            </div>

            {objectIssues.map((issue) => (
              <div key={issue.code} className="err block">
                {issue.message}
              </div>
            ))}

            <div className="section-title sub">Transform</div>
            <div className="row2">
              <label className="field-block">
                <span className="field-label">X</span>
                <input
                  className="input"
                  type="number"
                  defaultValue={single.inst.x}
                  key={`x-${single.inst.id}-${single.inst.x}`}
                  onBlur={(e) => onTransform(single, "x", e.target.value)}
                />
              </label>
              <label className="field-block">
                <span className="field-label">Y</span>
                <input
                  className="input"
                  type="number"
                  defaultValue={single.inst.y}
                  key={`y-${single.inst.id}-${single.inst.y}`}
                  onBlur={(e) => onTransform(single, "y", e.target.value)}
                />
              </label>
            </div>
            {single.def.editor.resizable && (
              <div className="row2">
                <label className="field-block">
                  <span className="field-label">Width</span>
                  <input
                    className={`input${hasIssue("width") ? " bad" : ""}`}
                    type="number"
                    defaultValue={single.width}
                    key={`w-${single.inst.id}-${single.width}`}
                    onBlur={(e) => onTransform(single, "width", e.target.value)}
                  />
                </label>
                <label className="field-block">
                  <span className="field-label">Height</span>
                  <input
                    className={`input${hasIssue("height") ? " bad" : ""}`}
                    type="number"
                    defaultValue={single.height}
                    key={`h-${single.inst.id}-${single.height}`}
                    onBlur={(e) => onTransform(single, "height", e.target.value)}
                  />
                </label>
              </div>
            )}

            {single.def.properties.length > 0 && (
              <>
                <div className="section-title sub">Properties</div>
                {single.def.properties.map((prop) => (
                  <div className="field" key={prop.key}>
                    {prop.type === "boolean" ? (
                      <label className="checkbox-row">
                        <Checkbox.Root
                          className="checkbox-box"
                          checked={effectiveValue(single.inst, prop.key) === true}
                          onCheckedChange={(c) => onBool(single.inst, prop, c === true)}
                        >
                          <Checkbox.Indicator>
                            <Check size={14} />
                          </Checkbox.Indicator>
                        </Checkbox.Root>
                        {prop.label}
                      </label>
                    ) : prop.type === "enum" ? (
                      <>
                        <span className="field-label">{prop.label}</span>
                        <Select.Root
                          value={str(single.inst, prop.key)}
                          onValueChange={(v) => onEnum(single.inst, prop, v)}
                        >
                          <Select.Trigger className={`select-trigger${hasIssue(prop.key) ? " bad" : ""}`}>
                            <Select.Value />
                            <Select.Icon>
                              <ChevronDown size={14} />
                            </Select.Icon>
                          </Select.Trigger>
                          <Select.Portal>
                            <Select.Content className="select-content" position="popper" sideOffset={4}>
                              <Select.Viewport>
                                {prop.options?.map((opt) => (
                                  <Select.Item key={opt} value={opt} className="select-item">
                                    <Select.ItemText>{opt}</Select.ItemText>
                                  </Select.Item>
                                ))}
                              </Select.Viewport>
                            </Select.Content>
                          </Select.Portal>
                        </Select.Root>
                      </>
                    ) : (
                      <>
                        <span className="field-label">{prop.label}</span>
                        <input
                          className={`input${hasIssue(prop.key) ? " bad" : ""}`}
                          type={prop.type === "number" ? "number" : "text"}
                          defaultValue={str(single.inst, prop.key)}
                          key={`${prop.key}-${single.inst.id}-${str(single.inst, prop.key)}`}
                          onBlur={(e) => onProp(single.inst, prop, e.target.value)}
                        />
                      </>
                    )}
                    {issueFor(prop.key) ? (
                      <div className="err">{issueFor(prop.key)!.message}</div>
                    ) : prop.help ? (
                      <div className="help">{prop.help}</div>
                    ) : null}
                  </div>
                ))}
              </>
            )}

            <div className="actions">
              <button className="btn" onClick={() => editor.duplicateSelection()}>
                Duplicate
              </button>
              <button className="btn danger" onClick={() => editor.deleteSelection()}>
                Delete
              </button>
            </div>
          </>
        ) : state.selectedIds.length > 1 ? (
          <>
            <div className="empty-state">
              <div className="empty-icon">◫</div>
              <div className="empty-title">{state.selectedIds.length} objects selected</div>
              <div className="empty-copy">Duplicate or delete the current selection.</div>
            </div>
            <div className="actions">
              <button className="btn" onClick={() => editor.duplicateSelection()}>
                Duplicate
              </button>
              <button className="btn danger" onClick={() => editor.deleteSelection()}>
                Delete
              </button>
            </div>
          </>
        ) : (
          <div className="empty-state">
            <div className="empty-icon">◇</div>
            <div className="empty-title">Nothing selected</div>
            <div className="empty-copy">
              Choose an object on the canvas or from the Scene tab to edit its properties.
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// apps/editor/src/app/inspector.component.ts
import { Component, computed, inject } from "@angular/core";
import { MatFormFieldModule } from "@angular/material/form-field";
import { MatInputModule } from "@angular/material/input";
import { MatSelectModule } from "@angular/material/select";
import { MatCheckboxModule } from "@angular/material/checkbox";
import { MatButtonModule } from "@angular/material/button";
import {
  effectiveValue,
  instanceSize,
  requireDefinition,
  setProperty,
  setTransform,
  type GameObjectDefinition,
  type LevelObjectInstance,
  type PropertyMeta,
  type ValidationIssue,
} from "@mmx/content-schema";
import { EditorService } from "./editor.service.js";
import { SpritePreviewComponent } from "./sprite-preview.component.js";

interface Single {
  inst: LevelObjectInstance;
  def: GameObjectDefinition;
  width: number;
  height: number;
}

/** Right panel: schema-generated inspector with inline validation. */
@Component({
  selector: "mmx-inspector",
  imports: [
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCheckboxModule,
    MatButtonModule,
    SpritePreviewComponent,
  ],
  template: `
    <div class="panel">
      <div class="scroll">
        @if (single(); as s) {
          <div class="header">
            <mmx-sprite-preview
              [definitionId]="s.def.id"
              [size]="56"
              [flip]="previewFlip(s)"
              [fallbackColor]="s.def.editor.color"
            />
            <div class="title">
              <span class="name">{{ s.def.icon }} {{ s.def.name }}</span>
              <span class="id">{{ s.inst.id }}</span>
            </div>
          </div>

          @for (issue of objectIssues(); track issue.code) {
            <div class="err block">{{ issue.message }}</div>
          }

          <div class="section-title sub">Transform</div>
          <div class="row2">
            <mat-form-field appearance="outline" subscriptSizing="dynamic">
              <mat-label>X</mat-label>
              <input
                matInput
                type="number"
                [value]="fmt(s.inst.x)"
                (change)="onTransform(s, 'x', $event)"
              />
            </mat-form-field>
            <mat-form-field appearance="outline" subscriptSizing="dynamic">
              <mat-label>Y</mat-label>
              <input
                matInput
                type="number"
                [value]="fmt(s.inst.y)"
                (change)="onTransform(s, 'y', $event)"
              />
            </mat-form-field>
          </div>
          @if (s.def.editor.resizable) {
            <div class="row2">
              <mat-form-field
                appearance="outline"
                subscriptSizing="dynamic"
                [class.bad]="hasIssue('width')"
              >
                <mat-label>Width</mat-label>
                <input
                  matInput
                  type="number"
                  [value]="fmt(s.width)"
                  (change)="onTransform(s, 'width', $event)"
                />
              </mat-form-field>
              <mat-form-field
                appearance="outline"
                subscriptSizing="dynamic"
                [class.bad]="hasIssue('height')"
              >
                <mat-label>Height</mat-label>
                <input
                  matInput
                  type="number"
                  [value]="fmt(s.height)"
                  (change)="onTransform(s, 'height', $event)"
                />
              </mat-form-field>
            </div>
          }

          @if (s.def.properties.length > 0) {
            <div class="section-title sub">Properties</div>
            @for (prop of s.def.properties; track prop.key) {
              <div class="field">
                @switch (prop.type) {
                  @case ("boolean") {
                    <mat-checkbox
                      [checked]="boolVal(s.inst, prop.key)"
                      (change)="onBool(s.inst, prop, $event.checked)"
                    >
                      {{ prop.label }}
                    </mat-checkbox>
                  }
                  @case ("enum") {
                    <mat-form-field
                      appearance="outline"
                      subscriptSizing="dynamic"
                      [class.bad]="hasIssue(prop.key)"
                    >
                      <mat-label>{{ prop.label }}</mat-label>
                      <mat-select
                        [value]="str(s.inst, prop.key)"
                        (selectionChange)="onEnum(s.inst, prop, $event.value)"
                      >
                        @for (opt of prop.options; track opt) {
                          <mat-option [value]="opt">{{ opt }}</mat-option>
                        }
                      </mat-select>
                    </mat-form-field>
                  }
                  @default {
                    <mat-form-field
                      appearance="outline"
                      subscriptSizing="dynamic"
                      [class.bad]="hasIssue(prop.key)"
                    >
                      <mat-label>{{ prop.label }}</mat-label>
                      <input
                        matInput
                        [type]="prop.type === 'number' ? 'number' : 'text'"
                        [value]="str(s.inst, prop.key)"
                        (change)="onProp(s.inst, prop, $event)"
                      />
                    </mat-form-field>
                  }
                }
                @if (issueFor(prop.key); as issue) {
                  <div class="err">{{ issue.message }}</div>
                } @else if (prop.help) {
                  <div class="help">{{ prop.help }}</div>
                }
              </div>
            }
          }

          <div class="actions">
            <button matButton (click)="service.duplicateSelection()">Duplicate</button>
            <button matButton class="danger" (click)="service.deleteSelection()">Delete</button>
          </div>
        } @else if (multi() > 1) {
          <div class="empty-state">
            <div class="empty-icon">◫</div>
            <div class="empty-title">{{ multi() }} objects selected</div>
            <div class="empty-copy">Duplicate or delete the current selection.</div>
          </div>
          <div class="actions">
            <button matButton (click)="service.duplicateSelection()">Duplicate</button>
            <button matButton class="danger" (click)="service.deleteSelection()">Delete</button>
          </div>
        } @else {
          <div class="empty-state">
            <div class="empty-icon">◇</div>
            <div class="empty-title">Nothing selected</div>
            <div class="empty-copy">
              Choose an object on the canvas or from the Scene tab to edit its properties.
            </div>
          </div>
        }
      </div>
    </div>
  `,
  styles: [
    `
      .panel {
        display: flex;
        flex-direction: column;
        height: 100%;
        background: var(--mmx-surface);
      }
      .section-title {
        text-transform: uppercase;
        letter-spacing: 0.6px;
        font-size: 10.5px;
        font-weight: 600;
        color: var(--mmx-text-3);
        padding: 11px 14px 7px;
      }
      .section-title.sub {
        border-top: 1px solid var(--mmx-border);
        margin-top: 8px;
      }
      .scroll {
        overflow-y: auto;
        min-height: 0;
        flex: 1;
      }
      .header {
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 16px 14px 12px;
        font-weight: 600;
      }
      .title {
        display: flex;
        flex-direction: column;
        gap: 3px;
        min-width: 0;
      }
      .name {
        line-height: 1.2;
      }
      .id {
        font-family: var(--mmx-mono);
        font-size: 10px;
        font-weight: 500;
        color: var(--mmx-text-3);
        word-break: break-all;
      }
      .row2 {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 8px;
        padding: 3px 14px;
      }
      .field {
        padding: 3px 14px;
      }
      mat-form-field {
        width: 100%;
        font-size: 12px;
      }
      .err {
        color: #ff9d9d;
        font-size: 10.5px;
        margin: 2px 0 4px;
      }
      .err.block {
        padding: 4px 12px;
      }
      .help {
        color: #6b7488;
        font-size: 10px;
        margin: 2px 0 4px;
      }
      .empty-state {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 64px 28px 24px;
        text-align: center;
      }
      .empty-icon {
        display: grid;
        place-items: center;
        width: 46px;
        height: 46px;
        margin-bottom: 15px;
        border: 1px solid var(--mmx-border-strong);
        border-radius: 13px;
        color: #7aaaff;
        background: linear-gradient(145deg, rgba(59, 130, 246, 0.15), rgba(59, 130, 246, 0.04));
        font-size: 22px;
      }
      .empty-title {
        margin-bottom: 6px;
        color: var(--mmx-text);
        font-weight: 650;
      }
      .empty-copy {
        max-width: 220px;
        color: var(--mmx-text-3);
        font-size: 11.5px;
        line-height: 1.55;
      }
      .actions {
        display: flex;
        gap: 8px;
        padding: 12px;
      }
      .actions button {
        flex: 1;
      }
      .actions .danger {
        color: #ff9d9d;
      }
      mat-checkbox {
        font-size: 12px;
      }
    `,
  ],
})
export class InspectorComponent {
  readonly service = inject(EditorService);

  readonly single = computed<Single | null>(() => {
    const s = this.service.state();
    if (s.selectedIds.length !== 1) return null;
    const inst = s.document.objects.find((o) => o.id === s.selectedIds[0]);
    if (!inst) return null;
    const def = requireDefinition(inst.definitionId);
    const size = instanceSize(inst);
    return { inst, def, width: size.width, height: size.height };
  });

  readonly multi = computed(() => this.service.state().selectedIds.length);

  previewFlip(s: Single): boolean {
    return s.def.category === "enemy" && effectiveValue(s.inst, "FacesRight") === true;
  }

  private readonly issues = computed<ValidationIssue[]>(() => {
    const one = this.single();
    if (!one) return [];
    return this.service.validation().issues.filter((i) => i.objectId === one.inst.id);
  });

  readonly objectIssues = computed(() => this.issues().filter((i) => !i.field));

  hasIssue(field: string): boolean {
    return this.issues().some((i) => i.field === field);
  }
  issueFor(field: string): ValidationIssue | undefined {
    return this.issues().find((i) => i.field === field);
  }

  fmt(value: number): string {
    return String(value);
  }
  str(inst: LevelObjectInstance, key: string): string {
    const v = effectiveValue(inst, key);
    return v === undefined || v === null ? "" : String(v);
  }
  boolVal(inst: LevelObjectInstance, key: string): boolean {
    return effectiveValue(inst, key) === true;
  }

  onTransform(s: Single, key: "x" | "y" | "width" | "height", event: Event): void {
    const next = Number((event.target as HTMLInputElement).value);
    if (!Number.isFinite(next)) return;
    const before = key === "x" ? s.inst.x : key === "y" ? s.inst.y : s[key];
    if (next === before) return;
    this.service.store.execute(setTransform(s.inst.id, { [key]: before }, { [key]: next }));
  }

  onProp(inst: LevelObjectInstance, prop: PropertyMeta, event: Event): void {
    const raw = (event.target as HTMLInputElement).value;
    const next = prop.type === "number" ? Number(raw) : raw;
    if (prop.type === "number" && !Number.isFinite(next as number)) return;
    this.service.store.execute(
      setProperty(inst.id, prop.key, "override", effectiveValue(inst, prop.key), next),
    );
  }

  onBool(inst: LevelObjectInstance, prop: PropertyMeta, checked: boolean): void {
    this.service.store.execute(
      setProperty(inst.id, prop.key, "override", effectiveValue(inst, prop.key) === true, checked),
    );
  }

  onEnum(inst: LevelObjectInstance, prop: PropertyMeta, value: string): void {
    this.service.store.execute(
      setProperty(inst.id, prop.key, "override", effectiveValue(inst, prop.key), value),
    );
  }
}
