// apps/editor/src/app/left-sidebar.component.ts
import { Component, computed, inject, signal } from "@angular/core";
import {
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  OBJECT_DEFINITIONS,
  effectiveValue,
  requireDefinition,
  type GameObjectDefinition,
  type LevelObjectInstance,
} from "@mmx/content-schema";
import { EditorService } from "./editor.service.js";
import { SpritePreviewComponent } from "./sprite-preview.component.js";

type SidebarTab = "palette" | "scene";

interface PaletteGroup {
  category: string;
  label: string;
  defs: GameObjectDefinition[];
}

interface SceneItem {
  inst: LevelObjectInstance;
  def: GameObjectDefinition;
}

@Component({
  selector: "mmx-left-sidebar",
  imports: [SpritePreviewComponent],
  template: `
    <div class="panel">
      <div class="tabs" role="tablist">
        <button
          type="button"
          role="tab"
          class="tab"
          [class.active]="tab() === 'palette'"
          [attr.aria-selected]="tab() === 'palette'"
          (click)="tab.set('palette')"
        >
          Object Palette
        </button>
        <button
          type="button"
          role="tab"
          class="tab"
          [class.active]="tab() === 'scene'"
          [attr.aria-selected]="tab() === 'scene'"
          (click)="tab.set('scene')"
        >
          Scene
          <span class="count">{{ sceneItems().length }}</span>
        </button>
      </div>

      @if (tab() === "palette") {
        <div class="search-wrap">
          <span class="search-icon">⌕</span>
          <input
            class="search-input"
            placeholder="Search objects…"
            aria-label="Search objects"
            [value]="query()"
            (input)="onSearch($event)"
          />
          @if (query()) {
            <button class="clear" type="button" aria-label="Clear search" (click)="query.set('')">
              ×
            </button>
          }
        </div>

        <div class="scroll">
          @for (group of grouped(); track group.category) {
            <div class="cat">{{ group.label }}</div>
            @for (def of group.defs; track def.id) {
              <button
                type="button"
                class="item"
                [class.active]="isPaletteActive(def.id)"
                (click)="service.selectPalette(def.id)"
                [title]="'Place ' + def.name"
              >
                <mmx-sprite-preview
                  [definitionId]="def.id"
                  [size]="28"
                  [fallbackColor]="def.editor.color"
                />
                <span class="item-name">{{ def.name }}</span>
                <span class="add">+</span>
              </button>
            }
          }
          @if (grouped().length === 0) {
            <div class="empty">No objects match your search.</div>
          }
        </div>
      } @else {
        <div class="scroll">
          @for (row of sceneItems(); track row.inst.id) {
            <button
              type="button"
              class="item"
              [class.active]="isSelected(row.inst.id)"
              (click)="service.focusObject(row.inst.id)"
              [title]="row.inst.id"
            >
              <mmx-sprite-preview
                [definitionId]="row.def.id"
                [size]="28"
                [flip]="sceneFlip(row)"
                [fallbackColor]="row.def.editor.color"
              />
              <span class="label">
                <span class="name">{{ row.def.name }}</span>
                <span class="meta">{{ row.inst.x }}, {{ row.inst.y }}</span>
              </span>
            </button>
          }
          @if (sceneItems().length === 0) {
            <div class="empty">No objects in the scene. Place one from the Object Palette.</div>
          }
        </div>
      }
    </div>
  `,
  styles: [
    `
      .panel {
        display: flex;
        flex-direction: column;
        height: 100%;
        background: var(--mmx-surface);
      }
      .tabs {
        display: flex;
        border-bottom: 1px solid var(--mmx-border);
        flex: none;
      }
      .tab {
        flex: 1;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 6px;
        padding: 11px 8px 9px;
        border: none;
        background: transparent;
        color: var(--mmx-text-3);
        font: inherit;
        font-size: 10px;
        font-weight: 700;
        letter-spacing: 0.6px;
        text-transform: uppercase;
        cursor: pointer;
        border-bottom: 2px solid transparent;
        margin-bottom: -1px;
      }
      .tab:hover {
        color: var(--mmx-text-2);
        background: var(--mmx-surface-hover);
      }
      .tab.active {
        color: #d8e7ff;
        border-bottom-color: var(--mmx-accent);
      }
      .count {
        font-family: var(--mmx-mono);
        font-size: 10px;
        font-weight: 500;
        letter-spacing: 0;
        text-transform: none;
        color: #6b7488;
        background: #1a2030;
        padding: 1px 5px;
        border-radius: 4px;
      }
      .tab.active .count {
        color: #93c5fd;
        background: #1c2c4a;
      }
      .search-wrap {
        display: flex;
        align-items: center;
        gap: 8px;
        height: 36px;
        margin: 12px 12px 7px;
        padding: 0 10px;
        border: 1px solid var(--mmx-border-strong);
        border-radius: 8px;
        background: var(--mmx-surface-raised);
        transition:
          border-color 120ms,
          box-shadow 120ms;
      }
      .search-wrap:focus-within {
        border-color: var(--mmx-accent);
        box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.12);
      }
      .search-icon {
        color: var(--mmx-text-3);
        font-size: 17px;
        transform: rotate(-20deg);
      }
      .search-input {
        min-width: 0;
        flex: 1;
        border: 0;
        outline: 0;
        background: transparent;
        color: var(--mmx-text);
        font: inherit;
        font-size: 12px;
      }
      .search-input::placeholder {
        color: var(--mmx-text-3);
      }
      .clear {
        border: 0;
        background: transparent;
        color: var(--mmx-text-3);
        cursor: pointer;
        font-size: 17px;
      }
      .scroll {
        overflow-y: auto;
        min-height: 0;
        flex: 1;
      }
      .cat {
        font-size: 10px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        color: var(--mmx-text-3);
        padding: 13px 14px 5px;
        font-weight: 700;
      }
      .item {
        display: flex;
        align-items: center;
        gap: 10px;
        width: calc(100% - 14px);
        min-height: 34px;
        margin: 1px 7px;
        padding: 5px 8px;
        border: 0;
        border-radius: 7px;
        background: transparent;
        font: inherit;
        text-align: left;
        cursor: pointer;
        font-size: 12.5px;
        color: var(--mmx-text-2);
        transition:
          background 100ms,
          color 100ms;
      }
      .item:hover {
        background: var(--mmx-surface-hover);
        color: var(--mmx-text);
      }
      .item.active {
        background: rgba(59, 130, 246, 0.16);
        color: #d8e7ff;
      }
      .swatch {
        display: grid;
        place-items: center;
        width: 24px;
        height: 24px;
        border-radius: 6px;
        flex: none;
        color: rgba(255, 255, 255, 0.92);
        font-size: 11px;
        box-shadow: inset 0 1px rgba(255, 255, 255, 0.22);
      }
      .item-name {
        min-width: 0;
        flex: 1;
      }
      .add {
        color: var(--mmx-text-3);
        opacity: 0;
        font-size: 17px;
      }
      .item:hover .add {
        opacity: 1;
      }
      .label {
        display: flex;
        flex-direction: column;
        gap: 1px;
        min-width: 0;
      }
      .name {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      .meta {
        font-family: var(--mmx-mono);
        font-size: 10px;
        color: #6b7488;
      }
      .item.active .meta {
        color: #93c5fd;
      }
      .empty {
        padding: 14px 12px;
        color: #6b7488;
        font-size: 12px;
      }
    `,
  ],
})
export class LeftSidebarComponent {
  readonly service = inject(EditorService);
  readonly tab = signal<SidebarTab>("palette");
  readonly query = signal("");

  readonly grouped = computed<PaletteGroup[]>(() => {
    const q = this.query().trim().toLowerCase();
    return CATEGORY_ORDER.map((category) => ({
      category,
      label: CATEGORY_LABELS[category] ?? category,
      defs: OBJECT_DEFINITIONS.filter(
        (d) =>
          d.category === category &&
          (!q || d.name.toLowerCase().includes(q) || d.category.includes(q)),
      ),
    })).filter((g) => g.defs.length > 0);
  });

  readonly sceneItems = computed<SceneItem[]>(() =>
    this.service.state().document.objects.map((inst) => ({
      inst,
      def: requireDefinition(inst.definitionId),
    })),
  );

  onSearch(event: Event): void {
    this.query.set((event.target as HTMLInputElement).value);
  }

  isPaletteActive(definitionId: string): boolean {
    const s = this.service.state();
    return s.activeTool === "place" && s.placingDefinitionId === definitionId;
  }

  isSelected(id: string): boolean {
    return this.service.state().selectedIds.includes(id);
  }

  sceneFlip(row: SceneItem): boolean {
    return row.def.category === "enemy" && effectiveValue(row.inst, "FacesRight") === true;
  }
}

// apps/studio/src/renderer/src/components/LeftSidebar.tsx
import { useMemo, useRef } from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import { Plus, Search, X } from "lucide-react";
import {
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  OBJECT_DEFINITIONS,
  effectiveValue,
  requireDefinition,
  type GameObjectDefinition,
  type LevelObjectInstance,
} from "@mmx/content-schema";
import { editor, useEditorSnapshot } from "../app/useEditor.js";
import { useUiStore } from "../store/uiStore.js";
import { cx, itemCls, panel, scroll } from "../ui.js";
import { SpritePreview } from "./SpritePreview.js";

const tabBase =
  "flex-1 flex items-center justify-center gap-1.5 pt-[11px] px-2 pb-[9px] bg-transparent text-[10px] " +
  "font-bold tracking-[0.6px] uppercase cursor-pointer border-b-2 -mb-px";
const tabCls = (active: boolean): string =>
  cx(tabBase, active ? "text-accent-fg border-accent" : "text-fg-3 border-transparent hover:text-fg-2 hover:bg-hover");

const cat = "text-[10px] uppercase tracking-[0.5px] text-fg-3 pt-[13px] px-3.5 pb-[5px] font-bold";
const emptyNote = "px-3 py-3.5 text-muted text-xs";
const itemName = "min-w-0 flex-1 whitespace-nowrap overflow-hidden text-ellipsis";

type PaletteRow =
  | { kind: "header"; key: string; label: string }
  | { kind: "def"; key: string; def: GameObjectDefinition };

type SceneRow = { inst: LevelObjectInstance; def: GameObjectDefinition };

/** Left dock: searchable, virtualized object palette + scene tree, in two tabs. */
export function LeftSidebar() {
  const snap = useEditorSnapshot();
  const tab = useUiStore((s) => s.sidebarTab);
  const setTab = useUiStore((s) => s.setSidebarTab);
  const query = useUiStore((s) => s.paletteQuery);
  const setQuery = useUiStore((s) => s.setPaletteQuery);

  const sceneRows = useMemo<SceneRow[]>(
    () =>
      snap.state.document.objects.map((inst) => ({
        inst,
        def: requireDefinition(inst.definitionId),
      })),
    [snap.state.document.objects],
  );

  return (
    <div className={panel}>
      <div className="flex border-b border-border flex-none" role="tablist">
        <button
          role="tab"
          className={tabCls(tab === "palette")}
          aria-selected={tab === "palette"}
          onClick={() => setTab("palette")}
        >
          Object Palette
        </button>
        <button
          role="tab"
          className={tabCls(tab === "scene")}
          aria-selected={tab === "scene"}
          onClick={() => setTab("scene")}
        >
          Scene{" "}
          <span
            className={cx(
              "font-mono text-[10px] font-medium tracking-normal normal-case px-[5px] py-px rounded",
              tab === "scene" ? "text-[#93c5fd] bg-selected" : "text-muted bg-[#1a2030]",
            )}
          >
            {sceneRows.length}
          </span>
        </button>
      </div>

      {tab === "palette" ? (
        <>
          <div className="flex items-center gap-2 h-9 mt-3 mx-3 mb-[7px] px-2.5 border border-border-strong rounded-lg bg-raised transition-[border-color,box-shadow] duration-[120ms] focus-within:border-accent focus-within:shadow-[0_0_0_3px_rgba(59,130,246,0.12)]">
            <Search size={16} className="text-[#7792bc]" />
            <input
              className="min-w-0 flex-1 border-0 outline-0 bg-transparent text-fg text-xs placeholder:text-fg-3"
              placeholder="Search objects…"
              aria-label="Search objects"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
            {query && (
              <button
                className="border-0 bg-transparent text-fg-3 cursor-pointer inline-flex"
                aria-label="Clear search"
                onClick={() => setQuery("")}
              >
                <X size={15} />
              </button>
            )}
          </div>
          <PaletteList query={query} snap={snap} />
        </>
      ) : (
        <SceneList rows={sceneRows} snap={snap} />
      )}
    </div>
  );
}

function PaletteList({
  query,
  snap,
}: {
  query: string;
  snap: ReturnType<typeof useEditorSnapshot>;
}) {
  const scrollRef = useRef<HTMLDivElement>(null);

  const rows = useMemo<PaletteRow[]>(() => {
    const q = query.trim().toLowerCase();
    const out: PaletteRow[] = [];
    for (const category of CATEGORY_ORDER) {
      const defs = OBJECT_DEFINITIONS.filter(
        (d) =>
          d.category === category &&
          (!q || d.name.toLowerCase().includes(q) || d.category.includes(q)),
      );
      if (defs.length === 0) continue;
      out.push({ kind: "header", key: `h:${category}`, label: CATEGORY_LABELS[category] ?? category });
      for (const def of defs) out.push({ kind: "def", key: def.id, def });
    }
    return out;
  }, [query]);

  const virtualizer = useVirtualizer({
    count: rows.length,
    getScrollElement: () => scrollRef.current,
    estimateSize: (i) => (rows[i].kind === "header" ? 28 : 36),
    overscan: 12,
  });

  const active = snap.state;
  const isActive = (id: string) =>
    active.activeTool === "place" && active.placingDefinitionId === id;

  if (rows.length === 0) {
    return (
      <div className={scroll} ref={scrollRef}>
        <div className={emptyNote}>No objects match your search.</div>
      </div>
    );
  }

  return (
    <div className={scroll} ref={scrollRef}>
      <div className="relative w-full" style={{ height: virtualizer.getTotalSize() }}>
        {virtualizer.getVirtualItems().map((v) => {
          const row = rows[v.index];
          const style = {
            position: "absolute" as const,
            top: 0,
            left: 0,
            width: "100%",
            transform: `translateY(${v.start}px)`,
            height: v.size,
          };
          if (row.kind === "header") {
            return (
              <div key={v.key} className={cat} style={style}>
                {row.label}
              </div>
            );
          }
          const def = row.def;
          return (
            <div key={v.key} style={style}>
              <button
                className={itemCls(isActive(def.id))}
                title={`Place ${def.name}`}
                onClick={() => editor.selectPalette(def.id)}
              >
                <SpritePreview definitionId={def.id} size={28} fallbackColor={def.editor.color} />
                <span className={itemName}>{def.name}</span>
                <span className="text-fg-3 opacity-0 inline-flex group-hover:opacity-100">
                  <Plus size={16} />
                </span>
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function SceneList({
  rows,
  snap,
}: {
  rows: SceneRow[];
  snap: ReturnType<typeof useEditorSnapshot>;
}) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const virtualizer = useVirtualizer({
    count: rows.length,
    getScrollElement: () => scrollRef.current,
    estimateSize: () => 40,
    overscan: 12,
  });

  const selected = new Set(snap.state.selectedIds);
  const sceneFlip = (row: SceneRow) =>
    row.def.category === "enemy" && effectiveValue(row.inst, "FacesRight") === true;

  if (rows.length === 0) {
    return (
      <div className={scroll} ref={scrollRef}>
        <div className={emptyNote}>No objects in the scene. Place one from the Object Palette.</div>
      </div>
    );
  }

  return (
    <div className={scroll} ref={scrollRef}>
      <div className="relative w-full" style={{ height: virtualizer.getTotalSize() }}>
        {virtualizer.getVirtualItems().map((v) => {
          const row = rows[v.index];
          const active = selected.has(row.inst.id);
          return (
            <div
              key={row.inst.id}
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                transform: `translateY(${v.start}px)`,
                height: v.size,
              }}
            >
              <button className={itemCls(active)} title={row.inst.id} onClick={() => editor.focusObject(row.inst.id)}>
                <SpritePreview
                  definitionId={row.def.id}
                  size={28}
                  flip={sceneFlip(row)}
                  fallbackColor={row.def.editor.color}
                />
                <span className="flex flex-col gap-px min-w-0">
                  <span className="whitespace-nowrap overflow-hidden text-ellipsis">{row.def.name}</span>
                  <span className={cx("font-mono text-[10px]", active ? "text-[#93c5fd]" : "text-muted")}>
                    {row.inst.x}, {row.inst.y}
                  </span>
                </span>
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}
