// apps/editor/src/app/toolbar.component.ts
import { Component, inject } from "@angular/core";
import { MatToolbarModule } from "@angular/material/toolbar";
import { MatButtonModule } from "@angular/material/button";
import { MatTooltipModule } from "@angular/material/tooltip";
import { MatDividerModule } from "@angular/material/divider";
import { MatMenuModule } from "@angular/material/menu";
import { EditorService } from "./editor.service.js";

@Component({
  selector: "mmx-toolbar",
  imports: [MatToolbarModule, MatButtonModule, MatTooltipModule, MatDividerModule, MatMenuModule],
  template: `
    <mat-toolbar class="bar">
      <div class="left">
        <div class="brand" aria-label="MMX Studio">
          <span>MMX <span class="accent">Studio</span></span>
        </div>

        <div class="group">
          <button
            class="text-action"
            matButton
            (click)="service.importJson()"
            matTooltip="Open a level JSON file"
          >
            Import
          </button>
          <button
            class="text-action save"
            matButton
            (click)="service.save()"
            matTooltip="Download level JSON (Ctrl+S)"
          >
            Save
            @if (service.dirty()) {
              <span class="dirty" aria-label="Unsaved changes"></span>
            }
          </button>
        </div>

        <mat-divider vertical />

        <div class="group">
          <button
            matIconButton
            [disabled]="!service.canUndo() || playing()"
            (click)="service.undo()"
            matTooltip="Undo (Ctrl+Z)"
            aria-label="Undo"
          >
            <span class="tool-icon">↶</span>
          </button>
          <button
            matIconButton
            [disabled]="!service.canRedo() || playing()"
            (click)="service.redo()"
            matTooltip="Redo (Ctrl+Shift+Z)"
            aria-label="Redo"
          >
            <span class="tool-icon">↷</span>
          </button>
        </div>

        <mat-divider vertical />

        <div class="group">
          <button
            matButton
            [class.active]="service.state().gridVisible"
            (click)="service.toggleGrid()"
            matTooltip="Toggle grid (G)"
          >
            <span class="toggle-dot"></span> Grid
          </button>
          <button
            matButton
            [class.active]="service.state().snapEnabled"
            (click)="service.toggleSnap()"
            matTooltip="Toggle snapping (Shift+G)"
          >
            <span class="toggle-dot"></span> Snap
          </button>
        </div>

        <mat-divider vertical />

        <div class="group zoom">
          <button
            matIconButton
            (click)="service.zoomBy(1 / 1.2)"
            matTooltip="Zoom out"
            aria-label="Zoom out"
          >
            <span class="tool-icon">−</span>
          </button>
          <span class="readout">{{ service.zoomPercent() }}%</span>
          <button
            matIconButton
            (click)="service.zoomBy(1.2)"
            matTooltip="Zoom in"
            aria-label="Zoom in"
          >
            <span class="tool-icon">+</span>
          </button>
          <button matButton (click)="service.fit()" matTooltip="Fit level to view (F)">Fit</button>
        </div>
      </div>

      <div class="center">
        <button
          matButton
          class="level-title"
          [matMenuTriggerFor]="levelsMenu"
          matTooltip="Select level"
        >
          <span class="level-kicker">LEVEL</span>
          <span>{{ service.levelTitle() }}</span>
          <span class="caret">⌄</span>
        </button>
        <mat-menu #levelsMenu="matMenu" panelClass="levels-menu">
          @for (level of service.levels; track level.key) {
            <button
              mat-menu-item
              [class.selected]="service.activeLevel() === level.key"
              (click)="service.openBuiltin(level.key)"
            >
              {{ level.name }}
            </button>
          }
        </mat-menu>
      </div>

      <div class="right">
        <button
          matButton="filled"
          [class.stop]="playing()"
          (click)="service.togglePlay()"
          matTooltip="Play / Stop (Ctrl+Enter)"
        >
          <span class="play-icon">{{ playing() ? "■" : "▶" }}</span>
          {{ playing() ? "Stop" : "Play" }}
        </button>
      </div>
    </mat-toolbar>
  `,
  styles: [
    `
      .bar {
        position: relative;
        z-index: 5;
        height: 56px;
        padding: 0 14px;
        display: flex;
        align-items: center;
        background: linear-gradient(180deg, #151b27 0%, #111722 100%);
        border-bottom: 1px solid var(--mmx-border);
        box-shadow: 0 4px 18px rgba(0, 0, 0, 0.22);
      }
      .left {
        display: flex;
        align-items: center;
        gap: 8px;
        flex: 1 1 auto;
        min-width: 0;
      }
      .center {
        position: absolute;
        left: 50%;
        transform: translateX(-50%);
        z-index: 1;
        padding: 0 6px;
        border: 1px solid var(--mmx-border);
        border-radius: 9px;
        background: #121823;
      }
      .right {
        display: flex;
        align-items: center;
        flex: none;
        margin-left: auto;
      }
      .brand {
        margin-right: 10px;
        font-size: 15px;
        font-weight: 700;
        letter-spacing: 0.25px;
        flex: none;
      }
      .brand .accent {
        color: #5b9cff;
      }
      .group {
        display: flex;
        align-items: center;
        gap: 2px;
      }
      .text-action {
        color: var(--mmx-text-2);
      }
      .save {
        gap: 7px;
      }
      .dirty {
        width: 6px;
        height: 6px;
        border-radius: 999px;
        background: #60a5fa;
        box-shadow: 0 0 8px rgba(96, 165, 250, 0.65);
      }
      .tool-icon {
        font-size: 18px;
        line-height: 1;
      }
      .readout {
        min-width: 42px;
        color: var(--mmx-text-2);
        font-family: var(--mmx-mono);
        font-size: 11px;
        text-align: center;
      }
      .level-title {
        max-width: 280px;
        color: var(--mmx-text);
        font-size: 13px;
        font-weight: 650;
        letter-spacing: 0.2px;
      }
      .level-kicker {
        margin-right: 10px;
        color: var(--mmx-text-3);
        font-size: 9px;
        font-weight: 700;
        letter-spacing: 0.8px;
      }
      .caret {
        margin-left: 2px;
        color: var(--mmx-text-3);
        font-size: 12px;
      }
      button.active {
        background: rgba(59, 130, 246, 0.16);
        color: #d8e7ff;
      }
      .toggle-dot {
        width: 5px;
        height: 5px;
        margin-right: 2px;
        border-radius: 50%;
        background: currentColor;
        opacity: 0.38;
      }
      button.active .toggle-dot {
        opacity: 1;
        box-shadow: 0 0 7px currentColor;
      }
      button.stop {
        --mat-sys-primary: #ef4444;
        --mat-sys-on-primary: #ffffff;
        background: #ef4444;
        color: #fff;
      }
      .right button {
        min-width: 88px;
        height: 36px;
        border-radius: 9px;
        font-weight: 700;
        letter-spacing: 0.15px;
        box-shadow: 0 5px 16px rgba(59, 130, 246, 0.22);
      }
      .play-icon {
        margin-right: 3px;
        font-size: 10px;
      }
      mat-divider[vertical] {
        height: 24px;
        margin: 0 2px;
      }
      @media (max-width: 1320px) {
        .zoom {
          display: none;
        }
      }
      @media (max-width: 1050px) {
        .level-kicker {
          display: none;
        }
        .center {
          left: 58%;
        }
      }
    `,
  ],
})
export class ToolbarComponent {
  readonly service = inject(EditorService);
  readonly playing = () => this.service.mode() === "play";
}

// apps/studio/src/renderer/src/components/Toolbar.tsx
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import {
  ChevronDown,
  FolderOpen,
  Grid3x3,
  Magnet,
  Maximize,
  Play,
  Redo2,
  Save,
  Square,
  Undo2,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import { editor, useEditorSnapshot } from "../app/useEditor.js";
import { btnCls, cx, ctxItemCls, menu } from "../ui.js";
import { Tooltip } from "./Tooltip.js";

const divider = "w-px h-6 mx-0.5 bg-border";
const group = "flex items-center gap-0.5";

/** Fixed command bar above the Dockview workspace. */
export function Toolbar() {
  const snap = useEditorSnapshot();
  const playing = snap.state.mode === "play";
  const zoomPercent = Math.round(snap.state.zoom * 100);

  return (
    <div className="relative z-[5] h-14 px-3.5 flex items-center gap-2 bg-gradient-to-b from-[#151b27] to-surface border-b border-border shadow-[0_4px_18px_rgba(0,0,0,0.22)]">
      <div className="flex items-center gap-2 flex-1 min-w-0">
        <div className="mr-1.5 text-[15px] font-bold tracking-[0.25px] flex-none" aria-label="MMX Studio">
          MMX <span className="text-accent-hover">Studio</span>
        </div>

        <div className={group}>
          <Tooltip label="Open a level JSON file">
            <button className={btnCls()} onClick={() => void editor.importJson()}>
              <FolderOpen size={15} /> Import
            </button>
          </Tooltip>
          <Tooltip label="Save level JSON (Ctrl+S)">
            <button className={btnCls()} onClick={() => editor.save()}>
              <Save size={15} /> Save
              {snap.dirty && (
                <span
                  className="w-1.5 h-1.5 rounded-full bg-[#60a5fa] shadow-[0_0_8px_rgba(96,165,250,0.65)]"
                  aria-label="Unsaved changes"
                />
              )}
            </button>
          </Tooltip>
        </div>

        <div className={divider} />

        <div className={group}>
          <Tooltip label="Undo (Ctrl+Z)">
            <button
              className={btnCls({ icon: true })}
              disabled={!snap.canUndo || playing}
              onClick={() => editor.undo()}
              aria-label="Undo"
            >
              <Undo2 size={16} />
            </button>
          </Tooltip>
          <Tooltip label="Redo (Ctrl+Shift+Z)">
            <button
              className={btnCls({ icon: true })}
              disabled={!snap.canRedo || playing}
              onClick={() => editor.redo()}
              aria-label="Redo"
            >
              <Redo2 size={16} />
            </button>
          </Tooltip>
        </div>

        <div className={divider} />

        <div className={group}>
          <Tooltip label="Toggle grid (G)">
            <button className={btnCls({ active: snap.state.gridVisible })} onClick={() => editor.toggleGrid()}>
              <Grid3x3 size={15} /> Grid
            </button>
          </Tooltip>
          <Tooltip label="Toggle snapping (Shift+G)">
            <button className={btnCls({ active: snap.state.snapEnabled })} onClick={() => editor.toggleSnap()}>
              <Magnet size={15} /> Snap
            </button>
          </Tooltip>
        </div>

        <div className={divider} />

        <div className={cx(group, "max-[1320px]:hidden")}>
          <Tooltip label="Zoom out">
            <button className={btnCls({ icon: true })} onClick={() => editor.zoomBy(1 / 1.2)} aria-label="Zoom out">
              <ZoomOut size={16} />
            </button>
          </Tooltip>
          <span className="min-w-[42px] text-fg-2 font-mono text-[11px] text-center">{zoomPercent}%</span>
          <Tooltip label="Zoom in">
            <button className={btnCls({ icon: true })} onClick={() => editor.zoomBy(1.2)} aria-label="Zoom in">
              <ZoomIn size={16} />
            </button>
          </Tooltip>
          <Tooltip label="Fit level to view (F)">
            <button className={btnCls()} onClick={() => editor.fit()}>
              <Maximize size={15} /> Fit
            </button>
          </Tooltip>
        </div>
      </div>

      <div className="absolute left-1/2 -translate-x-1/2 z-[1] px-1 border border-border rounded-[9px] bg-[#121823]">
        <DropdownMenu.Root>
          <DropdownMenu.Trigger asChild>
            <button
              className={cx(btnCls(), "gap-2 max-w-[280px] h-[34px] text-fg text-[13px] font-[650]")}
              aria-label="Select level"
            >
              <span className="text-fg-3 text-[9px] font-bold tracking-[0.8px]">LEVEL</span>
              <span>{snap.levelTitle}</span>
              <ChevronDown className="text-fg-3" size={13} />
            </button>
          </DropdownMenu.Trigger>
          <DropdownMenu.Portal>
            <DropdownMenu.Content className={menu} sideOffset={6} align="center">
              {editor.levels.map((level) => (
                <DropdownMenu.Item
                  key={level.key}
                  className={ctxItemCls(snap.activeLevelKey === level.key)}
                  onSelect={() => editor.openBuiltin(level.key)}
                >
                  {level.name}
                </DropdownMenu.Item>
              ))}
            </DropdownMenu.Content>
          </DropdownMenu.Portal>
        </DropdownMenu.Root>
      </div>

      <div className="flex items-center flex-none ml-auto">
        <Tooltip label="Play / Stop (Ctrl+Enter)">
          <button
            className={cx(
              "inline-flex items-center justify-center gap-1.5 min-w-[92px] h-9 px-2.5 rounded-[9px]",
              "border border-transparent text-white text-[12.5px] font-bold cursor-pointer transition-colors duration-100",
              playing
                ? "bg-danger shadow-[0_5px_16px_rgba(239,68,68,0.25)] hover:bg-[#f05555]"
                : "bg-accent shadow-[0_5px_16px_rgba(59,130,246,0.22)] hover:bg-accent-hover",
            )}
            onClick={() => editor.togglePlay()}
          >
            {playing ? <Square size={12} /> : <Play size={12} />}
            {playing ? "Stop" : "Play"}
          </button>
        </Tooltip>
      </div>
    </div>
  );
}
